### ISSUE TITLE
Custom NBT tags not saved.

### ISSUE THREAD

**Issue by Jamie-Jm3** [Multiverse/Multiverse-Inventories#107]
OK, so I have a plugin on my server that allows people to collect skulls, the server used many worlds so players are switching to and through each world. 

the issue I am having is when I have a custom NBT tagged item like a player skull with a skin if i were to swap worlds and swap back the head would revert to just a head no NBT tag. 

hope this can be fixed as its a huge issue

**Comment by dumptruckman** [comment]
Duplicate of #266
