### ISSUE TITLE
my portals all stopped working 

### ISSUE THREAD

**Issue by agsensi** [Multiverse/Multiverse-Inventories#112]
i guess im just a little confused i put in my inventories and now all my portals between worlds are not working and  i want to set it up so all but one world share invetories!  i have world + 4 other worlds that are regular worlds and then 1 world that is creative i just want the creative to have its own inv  so that they cant bring in and out from there  so if any one can help me with the 2 issues would be greatly appreciated

**Comment by dumptruckman** [comment]
No way MV-Inv would break portals.
