### ISSUE TITLE
Player inventories are not converting from yml to json.

### ISSUE THREAD

**Issue by cnaude** [Multiverse/Multiverse-Inventories#136]
I just upgraded to the latest version of Multiverse-Inventories 2.5-b335 (CB 1.4.7-R1.0). When a player joins for first time after the update their yml is converted to json in the current world. When they teleport to another world they lose their inventory in that world. 

I can see in the the world/worldname folder that their original yml is there. It creates a new json with no inventory items.

Is there an easy way to force the conversion for players?

**Comment by dumptruckman** [comment]
This won't be relevant if I revive this plugin.
