### ISSUE TITLE
Bed respawns deleting

### ISSUE THREAD

**Issue by kbryant** [Multiverse/Multiverse-Inventories#137]
Multiverse-Inventories v2.5-b335
Essentials vPre2.10.1.4
CraftBukkit v1.4.7-R1.1-SNAPSHOT

Essentials has a feature where you can set a "/home bed". I believe this is using the bed's respawn point as a home.

With this set in my MV-Inventories config: "use_game_mode_profiles: true"
Whenever a Player changes gamemodes, his bed respawn is deleted. "/home bed" is erased and the player has to re-set it.

**Comment by xtechgamer735** [comment]
Unable to reproduce this

**Comment by dumptruckman** [comment]
Closing since this is old and it may be fixed now. Open a new ticket if you have this problem with the latest dev builds.
