### ISSUE TITLE
Inventory lost when used with the Survival Games plugin

### ISSUE THREAD

**Issue by Gnorizo** [Multiverse/Multiverse-Inventories#138]
The MV-Inv and SG plugins appear to be incompatible and result in lost inventory when used together. I'm using CB 1.4.7-R1.0 with Multiverse-Inventories 2.5-b335 and Survival Games B-0.4.11 (http://dev.bukkit.org/server-mods/survival-games). 

Scenario 1 - I put both the main world ("world") and the SG lobby world ("sg-lobby") into the same mv-inv group ("default").

   a. When teleporting from world to sg-lobby, my inventory is unchanged. This is correct behavior.
   b. When teleporting into an SG game, the SG plugin clears my inventory and teleports me into the new world. This s correct behavior.
   c. When exiting the SG game and teleporting back into the SG lobby, my inventory is restored. This is correct behavior.
   d. Then when teleporting from "sg-lobby" to "world", the inventory is cleared and lost. This is incorrect behavior. The inventory shouldn't have changes, since the teleport is occuring between two worlds in the same group.

Scenario 2 - I put the SG  lobby world ("sg-lobby") into a separate group of it's own, with no other worlds in that group.

   a. When teleporting from world to sg-lobby, my inventory is cleared. This is correct behavior.
   b. When teleporting into an SG game, my inventory is still empty. This is correct behavior.
   c. When exiting the SG game and teleporting back into the SG  lobby, the inventory contains the items gathered from within the SG  game. This is incorrect behavior... the inventory should have been restored to being empty.
   d. When  teleporting from "sg-lobby" to "world",  the inventory still contains the items gathered within the SG game. This is incorrect behavior... the inventory should have been restored to the items in possession just prior to step (a) above.

In both scenarios, the items that were in possession prior to teleporting into the SG lobby are lost after teleporting back to the main world. This appears to be an incompatibility between the two plug-ins.

**Comment by dumptruckman** [comment]
To be honest this sounds like something Survival Games needs to fix. In any case, this is probably not relevant anymore so I'm closing the ticket. If it is relevant, let me know and I'll reopen this.
