### ISSUE TITLE
World inventories swapping/disappearing.

### ISSUE THREAD

**Issue by Beaupedia** [Multiverse/Multiverse-Inventories#141]
I have several players now who are losing their survival world inventories when coming back from a creative world. The creative world inventory is coming to survival, resulting in a difficult loss of their survival inventories.

11:52:54 PM
 CONSOLE:
[SEVERE] Cannot load plugins/Multiverse-Inventories/worlds/world/greencookieicing.json
11:52:54 PM
 CONSOLE:
JSON detected.
11:52:54 PM
 CONSOLE:
[SEVERE] Cannot load plugins/Multiverse-Inventories/worlds/world/greencookieicing.json
11:52:54 PM
 CONSOLE:
JSON detected.
11:52:54 PM
 CONSOLE:
[SEVERE] Cannot load plugins/Multiverse-Inventories/groups/survival/greencookieicing.json
11:52:54 PM
 CONSOLE:
JSON detected.
11:52:54 PM
 CONSOLE:
[INFO] greencookieicing was slain by Enderman
11:52:54 PM
 CONSOLE:
[SEVERE] Cannot load plugins/Multiverse-Inventories/groups/survival/greencookieicing.json
11:52:54 PM
 CONSOLE:
JSON detected.

**Comment by dumptruckman** [comment]
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.
