### ISSUE TITLE
2 Worlds Sharing XP? Bug?

### ISSUE THREAD

**Issue by greaperc4** [Multiverse/Multiverse-Inventories#143]
Well, i have more worlds, en 2 worlds have xp shared: i tried experience on shared xp and total_xp non of them works
when someone is switching to the 2nd world he stays at the XP he has in the first world
if i give him extra xp in the 2nd world and he switches back to the 1st world he will lose the XP i gave to him.
Why is This and could this be Fixed!??

thanks, Regards greaperc4

**Comment by dumptruckman** [comment]
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.
