### ISSUE TITLE
Merging inventories when teleporting between worlds

### ISSUE THREAD

**Issue by codyphobe** [Multiverse/Multiverse-Inventories#147]
I have a plot world using PlotMe, and a plain survival world, and for obvious reasons have the two worlds configured for separate inventories. However, I came across a little bug by accident and I'm not sure exactly if it's an issue with this plugin, but it's the first that came to mind. I teleported to my plot world, then immediately teleported back to the survival world because I remembered something I needed to do. I was experiencing a bit of lag after entering the command to teleport back, so I opened up my inventory (still in the plot world) and just as it opened, I was teleported. Upon entering the survival world, my plot world inventory was merged with my survival world inventory.

**Comment by dumptruckman** [comment]
Duplicate of #161
