### ISSUE TITLE
Different money in different worlds

### ISSUE THREAD

**Issue by oktay-sen** [Multiverse/Multiverse-Inventories#154]
Hello!
In my server, I have a skyblock world and a normal world. People can play survival in both worlds. I use multiverse inventories to separate these worlds, but i'd also like to separate money as well. I want to have auctions in skyblock world, but using a different currency. Can you guys do that?
What I simply want is this: A player will have x dollars in World A and World B, but y dollars in World C.
Thanks :D

**Comment by dumptruckman** [comment]
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.
