### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by AnthonyAMC** [Multiverse/Multiverse-Inventories#156]
Pastebin of error: http://pastebin.com/qv90VnPX
Spigot-b617
Multiverse-Core Version: 2.5-b652
Multiverse-Inventories Version: 2.5-b322
Multiverse-Portals Version: 2.5-b668

**Comment by dumptruckman** [comment]
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.
