### ISSUE TITLE
/mvinv group not working

### ISSUE THREAD

**Issue by SmugDragon** [Multiverse/Multiverse-Inventories#164]
Whenever I try to use the cmd mvinv group, delete, grp1 it always says the grp1 doesn't exist. Yet it is there when I list groups. I tried to create a new group, grp2, for the shares, but now there a a conflict between grp1 and grp2. And I cannot manually edit the group.yml file due to OS rights...any ideas what I need to try next? I just want to delete grp1 and keep grp2.

Thanks in advance,
~S~

**Comment by dumptruckman** [comment]
Should be fixed along with #223
