### ISSUE TITLE
One-sided inventory teleportation

### ISSUE THREAD

**Issue by lifehome** [Multiverse/Multiverse-Inventories#178]
Is it possible for players to only share the inventory when he/she goes through a multiverse-portal, and it would be seperated ever since?

To be accurate, for an example:

Tom goes through Portal Mortal2Upper, and the plugin syncs his inventory with the upper world. Afterward, his share group will be seperated from the Mortal world.

**Comment by dumptruckman** [comment]
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.
