### ISSUE TITLE
Breaking Blocks and dont drop.

### ISSUE THREAD

**Issue by dnk1994** [Multiverse/Multiverse-Inventories#183]
So i noticed that around the time i got multiverse inventories things were going great until a player told me he couldnt get wood. i investigated and saw that breaking any blocks from grass and wood ect. They dont drop, even for me who is the owner with all perms. So i took out multiverse out and things went back to normal things would drop however players from creative world can place stuff in enderchest and get away with it in the factions world. That hasnt happened yet.. not that i know of atleast. a few days later i redownloaded this plugin and let it config itself, and it turns out problem 1 is back where people break stuff but it wont drop in my main worlds which are called

groups:

  default:

```
worlds:

- pandora

- pandora_the_end

- pandora_nether

shares:

- all
```

note: i have 9 worlds in total.
3 are for factions - the pandora ones- which are the ones that wont drop items.
1 is for mobarena
1 is for creative plot
1 is for the awesome spawn i have
1 is for people to learn bending
1 is for the bending arenas

and even after i took those 3 worlds outa the config still problem persists.
any other worlds you break a block and it drops
And its not other plugins messing with it. Its this plugin
so now i had to remove it again and take out plotme and my creative world which players liked in order for my server to function properly. -.-

**Comment by CristianHG2** [comment]
I know this is a crazy old issue, but I also experienced this right after installing MV inventories on a fresh server. Did you figure out what the root cause was?
