### ISSUE TITLE
Speed and Slow potion effects not being saved with others

### ISSUE THREAD

**Issue by Al3xPro** [Multiverse/Multiverse-Inventories#185]
I am currently having problems with potion effects not working right and not removing when switching worlds. When players switch worlds they get unlimited of that effect in that world. This is a huge problem.

Thanks for any help.

Edit: Only for speed and slowness

**Comment by xtechgamer735** [comment]
Unable to reproduce this - potions are restricted to the correct worlds as per design.

**Comment by dumptruckman** [comment]
Closing since this is old and it may be fixed now. Open a new ticket if you have this problem with the latest dev builds.
