### ISSUE TITLE
Load inventory from world folder, not create new

### ISSUE THREAD

**Issue by Travja** [Multiverse/Multiverse-Inventories#189]
Basically I want the ability to set the players inventory to load from the .dat file when they first enter the world, while waiting for bukkit updates I put up a vanilla server for people to play on then import it to the server when bukkit updates.

**Comment by dumptruckman** [comment]
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.
