### ISSUE TITLE
[critical] issue when unloading creative world.

### ISSUE THREAD

**Issue by BukkitSmerf** [Multiverse/Multiverse-Inventories#195]
I creating new creative world so I must unload old creative world...
And when player logged out in Creative world then after join will be on spawn with creative inventory and gm.
1. Go to Creative
2. Log out (optional)
3. Unload world
4. Give diamonds to every-one

//Sorry for my English :(

**Comment by dumptruckman** [comment]
Pretty sure this was fixed.
