### ISSUE TITLE
A Feature Where Players in a Specific World not being Able to Edit their Inventory!

### ISSUE THREAD

**Issue by matthewthegoodman** [Multiverse/Multiverse-Inventories#202]
I would like a feature where any player in a specific world can not edit their inventory. For example, my server has a set inventory in a world and I would like no one to be able to move stuff around in their inventory in the "Spawn" world. 

Hope you can add this!
Matthew
matthewthegoodman@gmail.com

(PS: If your not looking into adding this feature, can u please give me a plugin that does this?)

**Comment by dumptruckman** [comment]
This sounds like a neat feature but I don't think it should be MV-Inv doing it. I'm not familiar with any plugins that do do this.
