### ISSUE TITLE
Inventory Issue

### ISSUE THREAD

**Issue by dodge4** [Multiverse/Multiverse-Inventories#203]
So i own a server with multiverse inventories, portals, and default
and when ever someone logs on gets stuff in their inventory and leaves then comes back their inventory is wiped

there is no error in the error log

these are all the other plugins i have:
World Edit
Simple-AutoSave
Vault
PermissionsEx
EchoPet
uSkyBlock
WorldGuard
SuperSkyBros
Marriage
PluginUpdater
PerWorldPlugins
Lockette
DarkCommands
SuperSpleef
Votifier
GAListiner
Essentials, Spawn, Protect, Chat
Factions
Enjin Minecraft Plugin

**Comment by dumptruckman** [comment]
Best guess is some other plugin is interacting poorly with MV-Inventories.

**Comment by TNTUP** [comment]
Oh lol didn't remember that issue I've replied to, not using it anymore since 2014 :/ sorry

**Comment by Reece1223** [comment]
Wow. This is old. Well at least MV-invs are working now :)

**Comment by andrewman542** [comment]
i am also still having this problem

**Comment by sorifiend** [comment]
Make sure you are using the latest dev build.
This issue has been fixed.

Build 443 is the newest at the time of writing:
https://ci.onarandombox.com/job/Multiverse-Inventories/443/
