### ISSUE TITLE
Add a way to convert MV Inventories data files to MC player .dat files

### ISSUE THREAD

**Issue by Ryanafordable** [Multiverse/Multiverse-Inventories#216]
I no longer want to use multiverse inventories and I want to convert the .json file back to the minecraft default .dat ones is there a way?

**Comment by RoosterBooster007** [comment]
This would be very helpful...

**Comment by x2110311x** [comment]
I 2nd this

**Comment by nicegamer7** [comment]
I am going to merge this with #88 since it's similar. Please go vote on whether you'd like to see this feature!
