### ISSUE TITLE
Console error PlayerChangeWorldEvent

### ISSUE THREAD

**Issue by AlanGreyjoy** [Multiverse/Multiverse-Inventories#218]
I have this error when people die or change worlds.

I belive it has something to do with RPGHealth http://dev.bukkit.org/bukkit-plugins/rpghealth/

http://pastebin.com/gY7aKJMt

Thanks guys.

**Comment by dumptruckman** [comment]
Somehow player data is being saved with invalid health values (less than 0 or more than 10). Hard to say what is going on here but it's likely the problem is related to a bug in another plugin.
