### ISSUE TITLE
last_location causing other plugins Teleporting to be overridden when moving worlds.

### ISSUE THREAD

**Issue by OmniTitan** [Multiverse/Multiverse-Inventories#219]
When a player tries to teleport to another player who is in a different world they get teleported either to their last location OR to some random location near where they last were, sometimes within blocks and thus suffocating and killing them.

Tried with Essentials TP commands.

**Comment by dumptruckman** [comment]
This is the unfortunate (and I believe documented) side effect of using last_location.
