### ISSUE TITLE
Errors changing world with v2-5 B335

### ISSUE THREAD

**Issue by lipe123** [Multiverse/Multiverse-Inventories#222]
I just dowloaded the 3 new downloads for core/inventories/netherportals but inventories is not happy.
I have the newest version of vault thats avail for download v1.2.31-b411

Console : [01:00:41 ERROR]: Could not pass event PlayerChangedWorldEvent to Multiverse-Inventories v2.5-b335
Console : org.bukkit.event.EventException
Console :   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-1308]
Console :   at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1308]
Console :   at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:30) ~[spigot.jar:git-Spigot-1308]
Console :   at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:482) [spigot.jar:git-Spigot-1308]
Console :   at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:467) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.PlayerList.moveToWorld(PlayerList.java:526) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.PlayerList.changeDimension(PlayerList.java:582) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.EntityPlayer.b(EntityPlayer.java:498) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.Entity.C(Entity.java:289) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.EntityLiving.C(EntityLiving.java:159) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.Entity.h(Entity.java:254) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.EntityLiving.h(EntityLiving.java:1272) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.EntityHuman.h(EntityHuman.java:162) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.EntityPlayer.i(EntityPlayer.java:256) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.PlayerConnection.a(PlayerConnection.java:343) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.PacketPlayInFlying.a(SourceFile:137) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.PacketPlayInFlying.handle(SourceFile:8) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.NetworkManager.a(NetworkManager.java:147) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.ServerConnection.c(ServerConnection.java:77) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.MinecraftServer.u(MinecraftServer.java:698) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.DedicatedServer.u(DedicatedServer.java:273) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.MinecraftServer.t(MinecraftServer.java:560) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.MinecraftServer.run(MinecraftServer.java:467) [spigot.jar:git-Spigot-1308]
Console :   at net.minecraft.server.v1_7_R1.ThreadServerApplication.run(SourceFile:617) [spigot.jar:git-Spigot-1308]
Console : Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.MultiverseCore.getBank()Lcom/fernferret/allpay/multiverse/GenericBank;
Console :   at com.onarandombox.multiverseinventories.api.share.Sharables$18.updateProfile(Sharables.java:533) ~[?:?]
Console :   at com.onarandombox.multiverseinventories.ShareHandler.updateProfile(ShareHandler.java:114) ~[?:?]
Console :   at com.onarandombox.multiverseinventories.ShareHandler.completeSharing(ShareHandler.java:77) ~[?:?]
Console :   at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:60) ~[?:?]
Console :   at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:189) ~[?:?]
Console :   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_45]
Console :   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
Console :   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_45]
Console :   at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_45]
Console :   at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:318) ~[spigot.jar:git-Spigot-1308]
Console :   ... 23 more

**Comment by dumptruckman** [comment]
Incompatible plugin versions.
