### ISSUE TITLE
Not able to edit group that is in the list

### ISSUE THREAD

**Issue by nathanperry2012** [Multiverse/Multiverse-Inventories#223]
I have a group in Multiverse Inventories that shows up in my list, but says '[group] does not exist!' when I try to edit/delete it.

-No I did not set it up in the config, I was using ingame commands
-The shares for the group still work, I just can't add worlds to it
-Was working fine until my dev team installed the plugin AdminAid
- However I can still edit the default group/create new groups, so this may not be the       problem

-Yes I made sure I spelled it right, even with proper caps in the right places

-Note- I would prefer to not reinstall the plugin as a lot of my players might lose inventories in specific groups

**Comment by dumptruckman** [comment]
We haven't been able to reproduce this so I'm going to leave it open as an outstanding bug. However, I'm not going to hold up the 2.5.0 release for it.

**Comment by benwoo1110** [comment]
Can't reproduce the bug as well and no new report on it, so I will be closing it due to inactivity. Do feel free to open a new issue if need. Thanks!
