### ISSUE TITLE
Per world economies

### ISSUE THREAD

**Issue by craftcraftmc** [Multiverse/Multiverse-Inventories#225]
Hi,

I can't figure out how to have new economies per world. Could you give me some help with making this happen? I found that you have to type /mvinv toggle economy but when I use it it doesn't change anything I get the message that pops up but when I go to the main world and give myself money then I go back to the multiverse world I have the same amount of money plus the money I added in the regular world. Isn't it not supposed to transfer over to the multiverse world? After trying what someone suggested on the plugin bukkit page this is what happened. It still has the same balance in both worlds. I'm running I think essentials economy and iconomy. I can use /bal and /money This is my groups http://pastebin.com/JF4UmxBC

I don't know if this is right though, and yes I do have the use_optionals: - economy

Also when I did this edit in this group file it made it so players bring inventories back across from world to world which didn't happen before.

**Comment by dumptruckman** [comment]
Please open a new ticket if you still care about this.
