### ISSUE TITLE
Add share for golden hearts from golden apples

### ISSUE THREAD

**Issue by gustebeast** [Multiverse/Multiverse-Inventories#228]
If a player eats a golden apple and gets the bonus hearts, it will not reset upon moving to a world separated by multiverse-inventories.

**Comment by dumptruckman** [comment]
Okay, this is a potion effect. Need to investigate why it's not being transferred. Probably related to #185.

**Comment by xtechgamer735** [comment]
Unable to reproduce this - golden hearts are shared or restricted where set.

**Comment by dumptruckman** [comment]
Closing since this is old and it may be fixed now. Open a new ticket if you have this problem with the latest dev builds.
