### ISSUE TITLE
Give money only in specific group

### ISSUE THREAD

**Issue by DanyBv** [Multiverse/Multiverse-Inventories#230]
Hello !

How can I give money to a player only in a group, not in the world where is him?

So if he is in Survival and I give him money I want the money to go in the Minigames group (all the minigames worlds).

Can you help me, please?

Thank you !

P.S.: Sorry if this content isn't suitable for a ticket.

**Comment by dumptruckman** [comment]
This feature doesn't exist. You can follow the feature request thread #274.
