### ISSUE TITLE
Crash Log please help!!

### ISSUE THREAD

**Issue by davewolax** [Multiverse/Multiverse-Inventories#233]
I see a lot of crash log in the console and I don't know what is happening and why. server actually doesn't crash, but it's spamming the console and I'm worried if something is wrong.
please help!! please
http://pastebin.com/L61J0CfP

**Comment by dumptruckman** [comment]
Will probably be fixed in #305.

**Comment by dumptruckman** [comment]
The version of MV-Inv you were using was not compatible with MC 1.7
