### ISSUE TITLE
Economy Support?

### ISSUE THREAD

**Issue by BobbyLent** [Multiverse/Multiverse-Inventories#241]
Hello MV Staff,

This is not an issue, but a feature request. I am requesting that you add in multiple world economy support to Multiverse-Inventories. It would be nice if you could make it so that players can have different balances in each world, and a customization area so you can link worlds together. For example, to link a factions world to a nether factions world. And, if possible, put a restriction so that players can't pay others in different worlds. I am trying to create a hub server without bungee, so that I can run things like Factions and Skyblock together, but I do not want players in the Factions world sending money to players in the Skyblock world, as it is not really fair because I want to set up the economy differently. Please consider this.

Regards,
Bobby Lent

**Comment by dumptruckman** [comment]
This feature is already supported, but may not have been when you opened this.
