### ISSUE TITLE
Custom items names bug

### ISSUE THREAD

**Issue by Eryk0201** [Multiverse/Multiverse-Inventories#245]
So I have several items with custom names on my server. For example it's enderpearl with name "Menu" and guns from CrackShot plugin. After server reload items have strange letters at the beginning of their name. My menu is doubling because I've got a plugin that gives you menu if you haven't got one. After several server reloads players have a lot of useless menus in their inventories. But larger problem is with guns. Players can buy guns from the store. When I reload the server, all guns have this letters at the beginning.  It's a problem because they aren't working anymore and players have to buy them again. 
![tt](https://cloud.githubusercontent.com/assets/8570529/4063378/3317ca98-2e07-11e4-8a0c-20b134a4aee4.png)

**Comment by Jeppa** [comment]
No, it's not.. 
I still have this bug with .383 build...

**Comment by Jeppa** [comment]
PS: this bug seems to happen on WIN-Servers only !?
My Linux-Server is running without that bug...  hmm

**Comment by Eryk0201** [comment]
Umm... thanks. It's weird to get a fix after almost 3 years xD Yet it seems so obvious. I can't check it if it works, I don't run the server now.

Also, I don't know if it makes a difference but #270 thread is newer than this one so it looks like that one should be tagged as duplicate. Still, I don't know if it matters, just saying.

**Comment by dumptruckman** [comment]
I recently cleaned up the issue tracker and worked from the most recent. So I made notes and labels and stuff and any older stuff I mostly referred to the newer tickets.
