### ISSUE TITLE
Inventories Sharing across all worlds

### ISSUE THREAD

**Issue by Maximuscr31** [Multiverse/Multiverse-Inventories#249]
I have a issue with inventories sharing across all worlds no matter what permission system. I have deleted pex, essentials, group manager, all the multiverse configs and just installed the multiverse jars. When it boots and makes it all fresh I have made portals and teleported to different worlds and the inventories always transfer. I am using cauldron  1.7.10 Forge 1231 patch (formerly mcpc+). I want to setup separate inventories for multiple worlds but no such luck yet. I get no errors. Any help will be greatly appreciated.

**Comment by dumptruckman** [comment]
Please open a new ticket if this is still an issue.
