### ISSUE TITLE
unable to edit an mvinv group

### ISSUE THREAD

**Issue by chillerkraft** [Multiverse/Multiverse-Inventories#254]
25.12 21:36:14 [Server] INFO There is no group with the name: MAIN
25.12 21:36:14 [Server] INFO MAIN
25.12 21:36:12 [Server] INFO Edit which group? MAIN
25.12 21:36:12 [Server] INFO edit
25.12 21:36:09 [Server] INFO What would you like to do? Create, Edit or Delete.  Enter ## at any time to cancel.

**Comment by dumptruckman** [comment]
Please open a new issue if you're still having issues.
