### ISSUE TITLE
Not working correctly

### ISSUE THREAD

**Issue by Minecraft930** [Multiverse/Multiverse-Inventories#257]
When I set the world to my PVE world and mirror all my other worlds besides my creative and minigames world it makes my spawn world, PVE world, PVE end and nether world, PVP world, PVP end and nether world are always separate but the only thing that worries me is that the end and nether are separate from their base worlds, please help me I can find no way to fix this.

**Comment by dumptruckman** [comment]
If you're still having trouble, please open a new issue.
