### ISSUE TITLE
Banners cause error in deserialization

### ISSUE THREAD

**Issue by gibbswe** [Multiverse/Multiverse-Inventories#259]
Hi! Getting this error when users change worlds: http://pastebin.com/yV6me2N1

**Comment by Trojaner25** [comment]
Error occurred while enabling <b>Achievements</b> v2.0.1-SNAPSHOT-71 (Is it up to date?)

This has nothing to do with Multiverse?

**Comment by gibbswe** [comment]
Sorry about that @Trojaner25, pasted wrong error. Same link, new error! (:

**Comment by dumptruckman** [comment]
Closing as duplicate of #252.
