### ISSUE TITLE
Custom items get all screwed up when changing worlds

### ISSUE THREAD

**Issue by xtomyserrax** [Multiverse/Multiverse-Inventories#261]
Hey! Could you possibly add compability with GuiShopManager plugin? ( http://dev.bukkit.org/bukkit-plugins/guishopmanager/ )

Because when i change the world with Multiverse-Inventories the item gets like this: http://imgur.com/0uzIT3i

Thanks!

**Comment by hockeymikey** [comment]
Make sure the server is using Unicode for encoding, that's the issue.

**Comment by dumptruckman** [comment]
Duplicate of #270
