### ISSUE TITLE
compile a new build with success result please :(

### ISSUE THREAD

**Issue by FlashLight34** [Multiverse/Multiverse-Inventories#268]
all in title :P

**Comment by FlashLight34** [comment]
up :|

**Comment by dumptruckman** [comment]
Why does this matter so much to you? Nothing has changed at all in many months.

**Comment by FlashLight34** [comment]
sorry i think its important :P so i use your plugin since 2 years and its the best plugin ever continu your good work man :)

**Comment by dumptruckman** [comment]
The thing is, I can just run the build process a few times and if we're lucky it will succeed. The only reason it is failing is because the unit tests have some weird problem I can't really explain.
