### ISSUE TITLE
Add command to edit player's inventory in a specific world.

### ISSUE THREAD

**Issue by LimitedGames** [Multiverse/Multiverse-Inventories#274]
Can you add a command that you can give Items in a world.
also if you are in an other world? or not online?
(its because of my votier)

**Comment by dumptruckman** [comment]
Maybe someday.

**Comment by DracarysPro** [comment]
We need a command to edit Offline Player's inventories. Would be cool if the command would behave like the essentials /invsee <player>, which opens the <player> inventory to you, which you can edit freely in-game, and then it saves upon closing.

**Comment by Jadiction** [comment]
Since it's unlikely this will be implemented. You could use Essentials (EssentialsX is the updated version) or a plugin to /invsee. With modification permissions, you do just this.
