### ISSUE TITLE
"Unknown Command" 

### ISSUE THREAD

**Issue by Adambuhl** [Multiverse/Multiverse-Inventories#275]
It just says "Unknown Command" when i do /mvinv and it doesnt create a folder in my plugins folder

**Comment by LosMapu** [comment]
I have the same problems... I don´t know if they changed the command with the updates or something

**Comment by dumptruckman** [comment]
This happens when a plugin fails to enable properly. Plugins don't enable properly typically because there was some error on startup. You need to look in your server log to find these errors. To get real help with these errors, you need to show them to the developer. Better luck next time.
