### ISSUE TITLE
How to "Separate" the money using MV Inventories for USkyBlock

### ISSUE THREAD

**Issue by PinoyLifeCraft** [Multiverse/Multiverse-Inventories#278]
Hellow guys i like to ask on how to separate the money on uskyblock, if the player has X money in spawnpoint then if they go in the uskyworld then they have there X money like 1M money :disappointed:
I already made an ticket in uskyblock and it said that it's not uskyblock issue :disappointed_relieved:

**Comment by PinoyLifeCraft** [comment]
and i recieve this
Im using Multiverse v2.5-b335
Could not pass event PlayerChangedWorldEvent to Multiverse-Inventories v2.5-b335 org.bukkit.event.EventException 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at net.minecraft.server.v1_8_R3.PlayerList.moveToWorld(PlayerList.java:628) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.teleport(CraftPlayer.java:471) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.teleport(CraftEntity.java:226) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at com.onarandombox.MultiverseCore.utils.SimpleSafeTTeleporter.safelyTeleport(SimpleSafeTTeleporter.java:215) [Multiverse-Core-2.5.jar:?] 	at com.onarandombox.MultiversePortals.listeners.PlayerListenerHelper.performTeleport(PlayerListenerHelper.java:44) [Multiverse-Portals-2.5.jar:?] 	at com.onarandombox.MultiversePortals.listeners.MVPPlayerMoveListener.playerMove(MVPPlayerMoveListener.java:137) [Multiverse-Portals-2.5.jar:?] 	at sun.reflect.GeneratedMethodAccessor148.invoke(Unknown Source) ~[?:?] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66] 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:270) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_66] 	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_66] 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_66] Caused by: java.lang.NoSuchMethodError: com.onarandombox.MultiverseCore.MultiverseCore.getBank()Lcom/fernferret/allpay/multiverse/GenericBank; 	at com.onarandombox.multiverseinventories.api.share.Sharables$18.updateProfile(Sharables.java:533) ~[?:?] 	at com.onarandombox.multiverseinventories.ShareHandler.updateProfile(ShareHandler.java:114) ~[?:?] 	at com.onarandombox.multiverseinventories.ShareHandler.completeSharing(ShareHandler.java:86) ~[?:?] 	at com.onarandombox.multiverseinventories.ShareHandler.handleSharing(ShareHandler.java:60) ~[?:?] 	at com.onarandombox.multiverseinventories.InventoriesListener.playerChangedWorld(InventoriesListener.java:189) ~[?:?] 	at sun.reflect.GeneratedMethodAccessor434.invoke(Unknown Source) ~[?:?] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_66] 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_66] 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24] 	... 28 more

**Comment by frizzbee30** [comment]
This isnt and 'inventory' issue, it's an econ issue. Do a search for multiworld money. You also need to log a separate issue on a desperate ticket I'm afraid.  :)

**Comment by dumptruckman** [comment]
MV-Inventory does support a simple version of multi-world economy, look in the configuration. The error you linked is because you're using outdated plugins. Update Multiverse-Core and Multiverse-Inventories from http://ci.onarandombox.com. However, Multiverse-Inventories has a significant dupe bug that is apparently unfixable and I would not recommend using it.
