### ISSUE TITLE
1.9 MV Inventories not holding when switching worlds or game mode...

### ISSUE THREAD

**Issue by austindkelly** [Multiverse/Multiverse-Inventories#282]
ERRORS: http://hastebin.com/vujinasomu.avrasm

Thought I would post here to let you know about errors that are occurring in the current build of MVinventories

**Comment by tim740** [comment]
This is because of the changes in 1.9 it shouldn't be to hard for them to fix this

**Comment by dumptruckman** [comment]
Update spigot. I'm told this should fix the issue.
