### ISSUE TITLE
How to transfer inventories?

### ISSUE THREAD

**Issue by Brushes** [Multiverse/Multiverse-Inventories#283]
Hi,

I recently copied over the inventories of players to a completely new server - expecting the inventories to copy over to the new server. But when I copy over all the files, nothing is there.

Please help ASAP.

thanks

**Comment by dumptruckman** [comment]
You will need to copy the player .dat files from your previous world. Those are what contain the current inventory. Please read this https://github.com/Multiverse/Multiverse-Inventories/wiki/Sharing-Details for more details on how things work.

**Comment by Brushes** [comment]
Ok thanks.

When I group together worlds, the inventories get cleared. On my previous server the worlds were grouped together but now that I have transferred them they are not grouped together and when I do all inventories get reset.

How do I do this without that happening?

Thanks.

**Comment by dumptruckman** [comment]
Closing since it's been over a year. If you're still using the plugin and still have this issue, feel free to open a new ticket.
