### ISSUE TITLE
Error occurred while disabling Multiverse-Inventories v2.5-b406 (Is it up to date?)

### ISSUE THREAD

**Issue by godsyn** [Multiverse/Multiverse-Inventories#287]
When stopping the server:
> [09:28:06] [Server thread/ERROR]: Error occurred while disabling Multiverse-Inventories v2.5-b406 (Is it up to date?)
> java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
>         at com.onarandombox.multiverseinventories.MultiverseInventories.onDisable(MultiverseInventories.java:76) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:293) ~[spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
>         at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
>         at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
>         at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
>         at org.bukkit.craftbukkit.v1_9_R1.CraftServer.disablePlugins(CraftServer.java:340) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
>         at net.minecraft.server.v1_9_R1.MinecraftServer.stop(MinecraftServer.java:454) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
>         at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:595) [spigot-1.9.jar:git-Spigot-3104eb1-bf43ca6]
>         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]
I believe **getOnlinePlayers()** was removed from 1.9 spigot/craftbukkit.

Server version:

> [09:31:45 INFO]: This server is running CraftBukkit version git-Spigot-3104eb1-bf43ca6 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
> [09:31:45 INFO]: Checking version, please wait...
> [09:31:45 INFO]: You are running the latest version

**Comment by dumptruckman** [comment]
Update to the dev build at http://ci.onarandombox.com

**Comment by godsyn** [comment]
http://ci.onarandombox.com/job/Multiverse-Inventories/lastSuccessfulBuild/artifact/target/Multiverse-Inventories-2.5.jar is currently b406, as is used in the ticket.

**Comment by sorifiend** [comment]
You will only see that message if you have an older version. Re-download the latest dev build and try again. Update multiverse core while you are at it to avoid any other issues.

**Comment by godsyn** [comment]
I just now downloaded it from the above URL, unzip'd the jar, and looked at line 76 of MultiverseInventories.java
`        for (final Player player : getServer().getOnlinePlayers()) {`

**Comment by sorifiend** [comment]
That line is correct for dealing with collections in the 1.9 API and in previous 1.8 builds.
I had the same issue on first update, but it should be fixed if you use the latest version of the build tools (Don't forget to use the '--rev 1.9' arg when building).

**Comment by dumptruckman** [comment]
See [this](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Server.html#getOnlinePlayers())? That is the method that is being called in the NEW builds. It returns a `Collection<? extends Player>`. The old builds were being built against a version of bukkit that used the same method but return `Player[]`. You can see in the stack trace that the method that cannot be found is the one that returns the array. The `[Lorg/bukkit/entity/Player` part indicates it is looking for a method that returns 'Player[]'. Are you satisfied yet?

**Comment by zombachu** [comment]
I'm able to reproduce this problem on my server as well. http://hastebin.com/wogereluza.avrasm
I'm using the latest build found on [jenkins](http://ci.onarandombox.com/job/Multiverse-Inventories/) (#408 at the moment), which is where I believe the issue arises.

In the code here on github it's calling the collection version of getOnlinePlayers(), but when I decompile the jar found on jenkins it's [very much using](http://puu.sh/nM0ky/09c254a7d8.png) the array form.

**Comment by LezChap** [comment]
I'm also getting this error running b408, the latest build found on jenkins, and the latest version of Spigot (This server is running CraftBukkit version git-Spigot-5a40365-f631379 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)).

**Comment by CCCCarsten** [comment]
Yes I have it too. Latest versions of mulitiverse and CraftBukkit version git-Spigot-a1b8bf3-f326992 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT).
