### ISSUE TITLE
Error disabling Multiverse-Inventories v2.5-b408 on server stop

### ISSUE THREAD

**Issue by emash** [Multiverse/Multiverse-Inventories#291]
Every time I stop my server i get error as in http://paste.ubuntu.com/15580867/
Everything else is working fine i just don't know why is it happening and does it mean something to me.

**Comment by Leiath** [comment]
I am having the same issue with Multiverse-Inventories v2.5-b408
http://pastebin.com/3RhAPHVq

**Comment by dumptruckman** [comment]
Multiverse-Inventories is no longer being maintained. We have found a good replacement that even supports importing your inventories from MV-Inventories: [PWI](https://www.spigotmc.org/resources/per-world-inventory.4482/)
