### ISSUE TITLE
Mutliverse inventory error causing lag.

### ISSUE THREAD

**Issue by killerkoda13** [Multiverse/Multiverse-Inventories#294]
For some reason boots seem to be throwing an error on my server these are the logs from the event:

http://www.ipaste.org/Cxk 
http://www.ipaste.org/Dxk

It seems to be an array out of bounds for the inventory. 
NOTE: Only throws when going in between dimensions.

**Comment by dumptruckman** [comment]
Multiverse-Inventories is no longer being maintained. We have found a good replacement that even supports importing your inventories from MV-Inventories: [PWI](https://www.spigotmc.org/resources/per-world-inventory.4482/)

**Comment by killerkoda13** [comment]
Thank you for your suggestion! :)
