### ISSUE TITLE
b410 need to be "1.9 fixed"

### ISSUE THREAD

**Issue by JohOply** [Multiverse/Multiverse-Inventories#297]
Hi guys,

There is an error when server stopped with b410 of MV-Inventories http://pastebin.com/4RLcx1iT . Need to use

> java -jar BuildData/bin/SpecialSource-2.jar map -m CraftBukkit/deprecation-mappings.csrg -i MyPlugin.jar -o MyPlugin-fixed.jar

Like explain here https://www.spigotmc.org/threads/minecraft-1-9-release.127186/ to be fixed :)

**Comment by dumptruckman** [comment]
Fixed in latest dev builds.
