### ISSUE TITLE
1.10 - Mind-Wipe?

### ISSUE THREAD

**Issue by nods0123** [Multiverse/Multiverse-Inventories#298]
So... I have two plugins that seem to mind-wipe whenever I go to the other worlds, I'm pretty sure this is an issue with Multiverse though... not 100% sure.. but yeah... Whenever I Claim area - Griefprevention, or create an interactive sign (Serversigns).. but I leave/restart (Not  sure.. I think Restart/Reload), it abandons the claim and clears the signs.. help?

**Comment by dumptruckman** [comment]
This has nothing to do with Multiverse.
