### ISSUE TITLE
Multiverse-Inventories "EDIT" options wont show

### ISSUE THREAD

**Issue by Denny7m** [Multiverse/Multiverse-Inventories#301]
I watched some tutorials on mvInv, but when i try /mvinv group it wont give me an option to "Edit"
Anyone knows how to fix this? Cuz i want to ''share" world Wild and world Survival, so what to do?

**Comment by sorifiend** [comment]
You need the right permissions to be able to use the command. What have you tried doing so far?

If in doubt just create the group in the plugins config file, rather than with in game commands.

**Comment by ScuroK** [comment]
@dumptruckman  i dont get it: Is MVINV continued or not??? there is only 1 alternative (pwi) but pwi is totally messed up and i really need a working inventory soulution.
