### ISSUE TITLE
Switch to using UUID instead of player names

### ISSUE THREAD

**Issue by dumptruckman** [Multiverse/Multiverse-Inventories#306]
The plugin should support UUIDs since that is the new way to do things.

**Comment by Portanna** [comment]
Will this enhancement support offline-mode uuids?

**Comment by dumptruckman** [comment]
I'm not entirely sure. It's going to support UUIDs that come from the Bukkit API. If Bukkit still provides a legitimate UUID for players in offline mode then it should work fine.
