### ISSUE TITLE
Receiving warning when switching game modes

### ISSUE THREAD

**Issue by VovKlee** [Multiverse/Multiverse-Inventories#318]
https://pastebin.com/1fZLHtBw

**Comment by sorifiend** [comment]
Do you have one of the latest builds? It should fix this issue and your other issue.

You can get the latest build here: [Multiverse-Inventories-2.5.0-SNAPSHOT](The latest builds should have fixed this issue: https://ci.onarandombox.com/job/Multiverse-Inventories/437/)

**Comment by VovKlee** [comment]
Ah, didn't see there was any later builds. Seems to have fixed it!
