### ISSUE TITLE
Heavy Timings - Lag

### ISSUE THREAD

**Issue by Portanna** [Multiverse/Multiverse-Inventories#320]
Using Multiverse-Inventories (Build 439) and the latest Multiverse-Core (Build 734)

PaperSpigot 1.11.2

![image](https://user-images.githubusercontent.com/20915660/28114127-be84f2d4-66ff-11e7-8b04-2846278329b9.png)

![image](https://user-images.githubusercontent.com/20915660/28128288-8c87c678-672f-11e7-9ce4-3c357271c267.png)

**Comment by dumptruckman** [comment]
Can you see if there are any large player data files? That is the only reason I imagine there bineg for any abnormal latency.

**Comment by Portanna** [comment]
Yes there is. Any way to delete old player data?

**Comment by dumptruckman** [comment]
How big is the largest single file you can find?

**Comment by Portanna** [comment]
In the **Multiverse-Inventories/players/** folder there are **108951 files**, in the **Multiverse-Inventories/groups/** folder there are **37502 files**, in the **Multiverse-Inventories/worlds/** folder there are more than **90000 files**.

The biggest file inside the **/players** folder is 59 bytes, the biggest file inside the **/worlds** folder is **46Kb**, the biggest file inside the **/groups** folder is **46Kb**.

The total size of the **/players** folder is **430Mb**, the total size of **/worlds** folder is **558Mb**, the total size of **/groups** folder is **172Mb**.

![image](https://user-images.githubusercontent.com/20915660/28167799-281be67a-67dd-11e7-95b3-000bbfc82315.png)


In case you wanna take a look, this is the folder (.tar.gz for ease of downloading): https://ufile.io/ipbuc

**Comment by dumptruckman** [comment]
Well, you don't have any abnormally large individual files so that shouldn't be the issue. I'll have to build in some special timings to figure out what part of the world change stuff is doing this. Don't expect anything soon.

Also, until I build in a purge feature you could look into something like [this](https://unix.stackexchange.com/questions/194863/delete-files-older-than-x-days).

**Comment by Portanna** [comment]
![image](https://user-images.githubusercontent.com/20915660/28247885-3e70a82a-6a3a-11e7-9ef5-377a268062d2.png)

Still having issues with lag generated by this event, even after reducing the Multiverse-Inventories database to just **15000** inventories, with a **total** size of **390 Mb**

**Comment by dumptruckman** [comment]
I have a strong suspicion that the only way to resolve this is to have some kind of profile caching so they're not being read from the disk every time you change worlds.
