### ISSUE TITLE
Survival inventory emty after renaming (logged out in creative-world)

### ISSUE THREAD

**Issue by MrSpock78** [Multiverse/Multiverse-Inventories#321]
Working well for month now on 1.11.2 (Multiverse-Inventories for 1.9 & 1.10 & 1.11 & 1.12 1.4). But found an issue:
A player logged out in my Creative World. He changed his Name and relogged again. His creative inventory was still there, but when he switched to a survival-world his survival inventory was cleared.
Why are all inventories still saved with playernames instead with UUIDs in 2017?
Any idea how to get his inventory back now? 

EDIT: Sorry, just saw that my version is very outdated :/
EDIT2: Tested with latest Multiverse-Core#736 and latest Multiverse-Inventories#439. The player still loses his survival-inventory after renaming.

**Comment by Jadiction** [comment]
Duplicate issue of https://github.com/Multiverse/Multiverse-Inventories/issues/329

**Comment by dumptruckman** [comment]
Notably, if you were using a build before #436 then there was nothing there to perform the migration. It's possible you could use the `mvinv migrate` command to remedy it now but no promises there.
