### ISSUE TITLE
Certain shares break entire groups

### ISSUE THREAD

**Issue by Davdinges** [Multiverse/Multiverse-Inventories#324]
Some shares break teleporting between worlds.
If you turn off bed_spawn in a share it simply refuses to teleport you to the target world and puts you back at your last known position.
There is currently no way not to share bed_spawns without breaking the access to entire worlds.

**Comment by dumptruckman** [comment]
Take a look at this: https://github.com/Multiverse/Multiverse-Inventories/wiki/Big-List-O-Shares#last_location
