### ISSUE TITLE
I noticed the dev build for this is being worked on again

### ISSUE THREAD

**Issue by axemwa** [Multiverse/Multiverse-Inventories#326]
I'm having some issues with my old world inventory manager, would it be ok if you could please add a converter for this plugin below. That way I'll be able to move over to yours without having to manually move all player inventories over, it would mean a lot.
https://www.spigotmc.org/resources/multiinv.56659/

**Comment by Jadiction** [comment]
There already appears to be a migration tool to import Multinv. More information can be found here: https://github.com/Multiverse/Multiverse-Inventories/wiki/Command-reference#import
I'll note that I have never tested this. I recommend you BACKUP your files before doing this.

**Comment by axemwa** [comment]
I'm pretty sure that these are 2 Multi-Inv links are different plugins made by different developers/authors.

**Comment by Jadiction** [comment]
I'm unsure, you could perhaps try the converter after a backup.
Unfortunately, I don't see this being added as it's very situational.

**Comment by axemwa** [comment]
All g ty for replying :)
