### ISSUE TITLE
Multiverse Inventories Does Not Work

### ISSUE THREAD

**Issue by BrightFyreXD** [Multiverse/Multiverse-Inventories#328]
Hi. My server uses multiverse core, inventories, and portals. However, whenever my players switched worlds or left, they would lose their stuff. This made them very frustrated. I tried several different inventory-world-sharing plugins, and none worked. I found a thread on spigot MC that I thought would help me, but it didn't whatsoever. I got multiverse inventories, and none of the world shares work, including inventories. I am trying to get my survival world to get it's own inventory. Please help. All of my multiverse plugins are up to date as well.
(my server is 1.12 and uses viaversion and viabackwards. I don't know whether that has anything to do with it or not)
**Plugin list**
BlockParty, Citizens, CorpseReborn, DailyRewards, EffectLib, EssentialsX, Grammar, HolographicDisplays, HubThat, KInvBackup, KitPvP, LaunchPadPlus, LibsDisguises, LuckPerms, MGOITC, MGSnake, MGSplegg, MassSayReborn, MinigamesLib, Multiverse-Core, Multiverse-Inventories, Multiverse-Portals, NoteBlockAPI, OldCombatMechanics, PlaceholderAPI, PluginConstructorAPI, ProtocolLib, RandomCoordinatesV2, ServerlistMOTD, SilkSpawners, SimplePrefix_Reloaded, SuperbVote, TNTRun, ThunderDeath, Vault, ViaVersion, VoxelSniper, murdermystery, nuvotifier, viabackwards, worldedit, and worldguard.

**Comment by Jadiction** [comment]
I'm currently using Multiverse-Inventories (and core) on my server with no problems with inventories. Can you output `/mv version -b`?
Also, can you try (after backing up) just using core and inventories without your other plugins? I personally know MV-Inventories and PWI work, just PWI is known to have issues currently.
MV-Inv should work fine. Perhaps it's a plugin messing with inventories.
