### ISSUE TITLE
importing inventories from Minecraft worlds 

### ISSUE THREAD

**Issue by MegaOddly** [Multiverse/Multiverse-Inventories#332]
I have tried for hours now and it just seems like i cant get this set up correctly 
I have it so my worlds are separate inventories now i just want to have the inventories to be what they where from the player.dat file but have had no luck getting it to import

**Comment by Jadiction** [comment]
This is not possible to do. (Importing from the player.dat). Once you install the plugin, you set up the configuration and their inventories from then will be separated, but you cannot import from vanilla's inventory system. If you'd like a full explanation on this, you may ask in the [Multiverse Discord](https://discord.gg/NZtfKky).

**Comment by dumptruckman** [comment]
To be clear, Bukkit based servers store the player's current inventory in player.dat in the default world. Multiverse-Inventories changes nothing about this behavior. Instead, the plugin swaps out the player's current inventory when they change worlds.
