### ISSUE TITLE
Issue on reloading plugin

### ISSUE THREAD

**Issue by RavenBlackwell** [Multiverse/Multiverse-Inventories#342]
Hi!

When I reload the plugin or when i reload the server the majuscules worldnames are turn on minuscule so my worlds are not included in the group that I want, for instance: Ressources on group 1 is turning on ressource when i reload the server(sorry for my english)

**Comment by Jadiction** [comment]
Closing old ticket. Make sure to update to the latest versions of Multiverse (Core, Inventories and any others you may use). Please open a new ticket if you believe you are encountering a bug. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
