### ISSUE TITLE
Multiverse-Inventories not working with Paper Spigot 1.15.2

### ISSUE THREAD

**Issue by cforsythe** [Multiverse/Multiverse-Inventories#345]
Hello, I tried using the latest stable build of Multiverse-Inventories on my Paper Spigot 1.15.2 server and for some reason it worked on 1.14.4, but when updating to 1.15.2 the inventories disappear in game. The files seemingly stay the same, but the in game inventory doesn't reflect the inventory stored in the file.

Is there a plan to fix this?

**Comment by metalshark** [comment]
It’s working fine here on 1.15.2 paper version #86. Have 15 worlds and the groupings of when inventories should go over or not all seem fine. There’s about a second lag where the old inventory shows then if updates for myself.

**Comment by Jadiction** [comment]
Closing old ticket. Make sure to update to the latest versions of Multiverse (Core, Inventories and any others you may use). Please open a new ticket if you believe you are encountering a bug. You can receive support on the [Multiverse Discord](https://discord.gg/NZtfKky).
