### ISSUE TITLE
name change bug

### ISSUE THREAD

**Issue by arts7493** [Multiverse/Multiverse-Inventories#349]
player’s inventory cleared after change nickname
use uuid please

**Comment by SirLemonade** [comment]
Have the same issue. Player changes their username and loses inventory. UUID support is essential. Please fix this bug.

**Comment by MegaNoam** [comment]
A known problem with the plugin, the dev unfortunately does not respond to messages

**Comment by Feldmarschall** [comment]
Same problem. 
plz fix it.

**Comment by Jadiction** [comment]
Duplicate issue of #329
