### ISSUE TITLE
Multiverse-Inventories doesn't prevent inventories from being "transferred" between worlds

### ISSUE THREAD

**Issue by JuiceeGreen** [Multiverse/Multiverse-Inventories#350]
I use the latest versions of Multiverse-Inventories and Multiverse-Core on Spigot 1.8.8. The problem I am facing is that the items and other aspects like health are being shared between worlds. I have negated the bypass permissions, removed OP and I placed the worlds in separate groups to prevent the transfer. Any help would be appreciated!

**Comment by Jadiction** [comment]
The latest versions of MV-Core and the sub-plugins aren't recommended for outdated MC versions such as 1.8.x. Multiverse does not take outdated versions into account for updates, so older versions of MV will need to be used. For additional assistance please refer to the [Multiverse Discord](https://discord.gg/NZtfKky).
