### ISSUE TITLE
Migrate Command doesn't work in certain situations 

### ISSUE THREAD

**Issue by nicegamer7** [Multiverse/Multiverse-Inventories#365]
Using the migrate command seems to do nothing in some circumstances, although, it says the command completes successfully. I'll update this with steps to reproduce soon.

**Comment by benwoo1110** [comment]
_soon_ 😆

**Comment by nicegamer7** [comment]
*soon*... for sure... lol.

I'm not sure this is even an issue anymore, you might've fixed it with #428, not sure. I'm too lazy to test, so I'll just assume it's fixed.
