### ISSUE TITLE
Inventories being shared through every world even when specified not to.

### ISSUE THREAD

**Issue by mikzyy** [Multiverse/Multiverse-Inventories#369]
So I installed Multiverse-Inventories (alongside Multiverse-Core) for my 1.8.8 server and when doing so, I needed it to group like this

Skyblock World Names:
voidspawn
daboys
daboys_nether

PvP World Names:
pvpspawn
pvp

I need anything earned from Skyblock (like xp, inventory, etc.) to be kept in the worlds for Skyblock World Names. Then, if they teleport to PvP, i need everything from the PvP world to be kept in the worlds for PvP World Names and not have skyblock items. 

After looking into this and trying it, it never worked. So, I started to question if it was the default world (level-name) thats set in the server.properties: "world". Since the default world is "world", will that mess up stuff like not being able to seperate inventores per world?

**Comment by nicegamer7** [comment]
Do you still have the default group? The default group is automatically created when you install the plugin.
