### ISSUE TITLE
Add command to modify xp per-world?

### ISSUE THREAD

**Issue by KAGamerAlex** [Multiverse/Multiverse-Inventories#37]
I'm requesting a command be made that allows you to give a player xp per-world.
So for example the command would be like: /xp (player) (amount) (world)
and if that world is in a group where the xp is shared among worlds, it would be shared.

**Comment by dumptruckman** [comment]
Related to #274.

**Comment by Jadiction** [comment]
Since it's unlikely this will be implemented. You could use Essentials (EssentialsX is the updated version) or a plugin to give exp.
