### ISSUE TITLE
Inventory not always saving

### ISSUE THREAD

**Issue by kOFReadie** [Multiverse/Multiverse-Inventories#371]
For some reason when I leave my world the inventory wont save yet when I switch worlds it SOMETIMES saves. This is annoying because I loose my progress when I rejoin and it also allows for item duping because you can drop the item, leave, rejoin and now you have double. [Video](https://streamable.com/ygvwhd)

**Comment by Crosis47** [comment]
I found this was happening to me only when disconnecting and rejoining the server. I found the issue to be cause by game mode profiles. If that is disabled it seems to fix the issue.

**Comment by benwoo1110** [comment]
Similar to #354
