### ISSUE TITLE
Multiverse Inv doesnt count multiverse worlds

### ISSUE THREAD

**Issue by Wynnevir** [Multiverse/Multiverse-Inventories#377]
Multiverse inventories will share the default worlds but not any world I create with multiverse. Ive tried adding them to the default group, making a new group - but i can not get it to share any new world i make.

**Comment by benwoo1110** [comment]
You can see how to set shares here: https://github.com/Multiverse/Multiverse-Core/wiki/Basics-(Inventories)

Closing this issue due to the lack of information. Please open a new issue and follow the issue template if needed. Thanks!
