### ISSUE TITLE
last_location per world

### ISSUE THREAD

**Issue by ArvickC** [Multiverse/Multiverse-Inventories#388]
### Feature request

**Feature description**
Have Last_Location disable per world option, so how it works is say i have a lobby, and that lobby has "last_location" disabled, then i have a survival world, and that world has "last_location" enabled

**How the feature is useful**
This is useful because if you have a lobby world and a survival world, you wouldn't want to spawn back where you were before in the lobby...

**Comment by nicegamer7** [comment]
This is already possible, but is currently broken because of #367.

**Comment by ArvickC** [comment]
Oh... Sorry!
