### ISSUE TITLE
Multiverse Inventories sharing over every world

### ISSUE THREAD

**Issue by MCDoerfi** [Multiverse/Multiverse-Inventories#389]
#182 # Information

* **git-Paper-157 (MC: 1.16.2) (Implementing API version 1.16.2-RO.1-SNAPSHOT):** 

* **https://pastebin.com/86qLBB4W** 

* **https://gist.github.com/MCDoerfi/04a41743fe7894e7613ea73e1bc953db** 

### Help request

**I installed Multiverse Inventories yesterday and everything went good, but when I logged in today, the plugin didn't work properly anymore, it just didn't seperate anything between worlds. I can still use the /mvinf group command and everything, the groups are fine too, but it just doesn't do it. Edit: it works fine for my friends**

**I tried everything from reinstalling to other plugins, but nothing worked **

**Screenshots**

**Comment by benwoo1110** [comment]
see #374

**Comment by benwoo1110** [comment]
For now there is a hotfix, you can get it at http://ci.onarandombox.com/view/Multiverse/job/Multiverse-Inventories/
