### ISSUE TITLE
last_location is complicated and is not working properly

### ISSUE THREAD

**Issue by eliyash31** [Multiverse/Multiverse-Inventories#405]
Multiverse 4.1.1 Snapshot b777
Paper Spigot version 1.16.3

Hello I need help about MV Inventories
Here I have group of worlds 
groupname: default
world
wild
note: last_location is not shared

optionals_for_ungrouped_worlds: true
now I have another world named mobarena that is not shared or doesn't have a group. 

This is what happens
world and wild last_location is saved or worked

However in mobarena last_location is still working. I tried setting optionals_for_ungrouped_worlds: false
but the world and wild last_location will not work even though they have last_location shared enabled, and also mobarena world last_location is not working (which is this is what I want) but I don't want that the world and wild last_location is not working :frowning: even though I already add last_location to shares with the groupname default

What I want is make world and wild last_location enabled but except for mobarena. How could I fix this problem?

btw I also tried setting optionals_for_ungrouped_worlds: true
with world and wild grouped together but setting the last_location to false (or last_location isn't shared)
and also mobarena as a separate group but last_location is shared or set to true. 

this happens : world and wild last_location worked and still mobarena last_location also worked! even though I already added last_location to it :(

How come world and wild last_location worked when last_location is set to false and mobarena last_location also is working even though its last_location was set to false

**Comment by kccricket** [comment]
I'm noticing this, as well. last_location is enabled as an optional, but is not added as a share for two of three groups. last_location is still taking effect for those groups where it's not enabled.

https://gist.github.com/kccricket/88960d96e92402b564ef4d1eb8fb3815

**Comment by benwoo1110** [comment]
> I'm noticing this, as well. last_location is enabled as an optional, but is not added as a share for two of three groups. last_location is still taking effect for those groups where it's not enabled.

This is an expected behaviour as the last location is enabled globally, removing it as a share just means each world in that group has its own last location. Tho maybe it's possible to have a config option to change this. 

However, what you are saying is a separate issue. This issue seems to be `optionals_for_ungrouped_worlds` setting not working as expected. So I suggest create a new issue for that @kccricket

**Comment by nicegamer7** [comment]
I'm going to mark this issue as stale. If you're still experiencing this, please open a new issue and fill out the issue template.
