### ISSUE TITLE
Cannot place armor stands in default world group - overworld/nether/end

### ISSUE THREAD

**Issue by Paistecrafter** [Multiverse/Multiverse-Inventories#441]
Hi so I've got a main world and a minigames world and needed a way for players' inventories to be handled separately to avoid duping / confusion when switching. Downloaded this, config'd it, works perfect, does as intended, all good.

1 bad side effect.

I can no longer place armor stands in the 3 main dimensions of the default world group defined in the plugin. I am fairly confident the cause originates from this plugin because I am able to place armor stands in my minigames world which is not a part of the default group, plus the problem began immediately after implementing this plugin. I thought it might be some world guard flag causing the issue, but I cant seem to find anything that suggests that. Anyone had this happen before? Any help greatly appreciated, not sure how to debug. Thanks much

Paiste_

**Comment by benwoo1110** [comment]
multiverse inventories doesn't have any logic in the code to block armour stands, unless you can reproduce this issue on the latest version of mv with only mv plugins installed on your server, I will close this issue.
