### ISSUE TITLE
Player data (Inventory, Enderchest and Achievements) erased when changing between worlds

### ISSUE THREAD

**Issue by joex92** [Multiverse/Multiverse-Inventories#442]
Everytime a player change between worlds the inventory and enderchest are erased... 
i don't know why is this happening, the server was fine an hour ago before updating other plugins that have nothing to do with inventories and enderchest... what do I do?

**Comment by benwoo1110** [comment]
Please follow the issue template and check the console for errors.

**Comment by joex92** [comment]
### Information

* **Server version:** 
* `23.03 12:11:10 [Server] INFO This server is running Yatopia version git-Yatopia-ver/1.16.5-42 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
23.03 12:11:10 [Server] INFO Previous version: git-Tuinity-"8954b61" (MC: 1.16.4)
23.03 12:11:10 [Server] INFO You are running the latest version`

* **Full output of `/mv version -p`:** 
* https://paste.gg/p/anonymous/6556b9b3411e4769a811b8bde97a5df5

* **Server log:** 
* https://gist.github.com/joex92/ce9bad757a3f648a050604804844fc75

### Details
I was **`not able`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
an hour before updating some plugins, everything was working good with no problems, but after updating, for some reason, player data (Inventory and enderchest) are completely deleted when changing between worlds (Nether and End included) either using `/tp` command or using portals. Also, it seems that the achievements are reset too, everytime I get inside the nether, I get the achievement...

**Steps to reproduce**  
latest update up to Jan 20th of the following plugins with no issues: BKCommonLib, MyCommand, LuckPerms, WorldEditSelectionVisualizer, Simple Elevator, SkinRestorer, Dimensions, Dangerous Caves 2, AutoPluginLoader (auto reload disabled), EconomyShopPlugin, FAWE, DiscordSRV, and all BentoBox plugin and addons. After updating these plugins, Multiverse begun acting up.

**Expected behavior**  
player Inventory being deleted when changing between worlds

**Screenshots**  
objects in inventory
![2021-03-23_11 36 13](https://user-images.githubusercontent.com/645579/112183210-08133d80-8bcc-11eb-8e72-1bdebe79ad7a.png)

immediately after crossing through the nether portal 
![2021-03-23_11 36 18](https://user-images.githubusercontent.com/645579/112183229-0c3f5b00-8bcc-11eb-9df3-b37fef0c09d1.png)

**Comment by benwoo1110** [comment]
Did this issue happen after you update to Yatopia? Bcu Yatopia is know to be unstable and cause such weird issues.

**Comment by joex92** [comment]
I've been using Yatopia for 2-3 years... with no problems at all... I thought about that and tried Tuinity (which is why /version shows that) and got the same result... I'm going to try Paper, but I believe it will be the same result...

**Comment by joex92** [comment]
tried with Paper:

items on Inventory
![2021-03-23_11 54 40](https://user-images.githubusercontent.com/645579/112185957-b02a0600-8bce-11eb-958b-2460a6128977.png)

immediately after crossing the portal
![2021-03-23_11 54 51](https://user-images.githubusercontent.com/645579/112185980-b4562380-8bce-11eb-856a-40b3ae92c67d.png)

**Comment by benwoo1110** [comment]
From your mv-inv setup, I dont see a group with worlds `NewCorona` and `TheNether`

**Comment by joex92** [comment]
that's weird... because according to this: 
![2021-03-23_12 07 47](https://user-images.githubusercontent.com/645579/112187885-7eb23a00-8bd0-11eb-8e26-5047d9bff4e5.png)
the group exists... the enderchest is on a global group with all worlds as a way to share items between worlds... (Bentobox worlds and lobby world)

**Comment by joex92** [comment]
do I have to create the groups again?

**Comment by benwoo1110** [comment]
I suggest testing with only mvm plugins installed then, since your startup logs have plenty of non-mv errors. Also I gussed the worldname from your scoreboard, apparently its not the actual worldname known by mv?

**Comment by joex92** [comment]
in the scoreboard I'm using the display name placeholder, not the world name placeholder... those errors you mentioned were there before the issue... so yeah... worst case scenario would be that the player data got kinda corrupted... but I don't believe that would be the case... but I'll try... although that would take me a bit of extra time...

**Comment by joex92** [comment]
oooook... I believe I found the problem... so while thinking about the plugins I updated, there was 1 that I thought it could be the problem... and indeed it was... I feel like a moron for not reading each BentoBox addon when it was almost obvious... there's a BentoBox addon called InvSwitcher, seems to work almost the same as Multiver-Inventories but for its own worlds... I deleted that Addon and the issue was solved... i just downloaded all the addons and add it to the server because that addon wasn't there before... anyways, thanks... one of the best plugin developer supports for responding quick... I'll close it... 

I guess the solution is: **Don't use 2 or more multi inventory plugins at the same time**
