### ISSUE TITLE
Load Backups

### ISSUE THREAD

**Issue by masterhacka** [Multiverse/Multiverse-Inventories#449]
I am using Multiverse-Inventories and don_t get why there is stored the inventories in each world or group but when changing it, nothing happens. If it only works when changing the player.dat in the main world, why are the Inventory items storen too in Multiverse-Inventories?

**Comment by benwoo1110** [comment]
You can not import/merge your vanilla inventories with Multiverse-Inventories. Once you install Multiverse-Inventories, your players will log in with the inventories they previously had.

Bukkit based servers store the player's current inventory in player.dat in the default world. Multiverse-Inventories changes nothing about this behavior. Instead, the plugin swaps out the player's current inventory when they change worlds.
