### ISSUE TITLE
Multiverse Inventories using the wrong inventory if logging out in the nether

### ISSUE THREAD

**Issue by IDzyre** [Multiverse/Multiverse-Inventories#452]
### Information

Server version: git-paper-143 (1.15.2)

Full output of `/mv version -p`: http://pastie.org/p/0DQmQerIgRkQ64Xvb28LEw

Server log: https://gist.github.com/IDzyre/b017166d7670de02c1750106c3579bf5

### Details
I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
If you have multiverse inventories on your server, and you have it set to spawn you at a lobby, if you disconnect or go to the lobby from a nether world linked to a survival world, and you go through a multiverse portal to the survival world, you will have your lobby inventory not the survival inventory.

**Steps to reproduce**  
I linked my survival nether world and my survival world with multiverse nether portals, and using groups shared inventory and last location. Once you go to the nether, and go to the lobby, if you go back to the survival world, it will take you to the nether, and give you the inventory you had in the lobby world. 

**Expected behavior**  
Have the survival inventory be restored even if you log off and respawn in the lobby. 

**Screenshots**  
I don't have screenshots but I have a video

https://youtu.be/A5inROF3GT8

**Comment by benwoo1110** [comment]
1. Update MV, some of your mv modules are outdated. http://ci.onarandombox.com/view/Multiverse/
2. What is your server specs? It's lagging so badly...

**Comment by benwoo1110** [comment]
No reply so... I assume its fixed...?
