### ISSUE TITLE
Where is Multiverse-Inventories data stored (need to load a backup)

### ISSUE THREAD

**Issue by 0ofland** [Multiverse/Multiverse-Inventories#471]
Quick question: all our players inventories got cleared. Might not have been multiverse inventories, idk yet. So my question is does multiverse inventories store data outside of the main plugin folder (Multiverse-Inventories) or does it use like mysql or another external database? Just need to know so I can troubleshoot.

**Comment by benwoo1110** [comment]
mvinv stores all data in its own folder only.
