### ISSUE TITLE
My Inventry is getting reset everytime i join the server when i join survival my inventry is gone! (Paper 1.16.5)

### ISSUE THREAD

**Issue by Aabiskar10** [Multiverse/Multiverse-Inventories#472]
### Information

* **Server version:** 1.16.5

* **Full output of `/mv version -p`:** 

* **Server log:** 

### Help request

**Problem**

**What I have tried**

**Screenshots**

**Comment by benwoo1110** [comment]
Closing as issue template is not filled.
