### ISSUE TITLE
Inventory breaks when player change their name

### ISSUE THREAD

**Issue by holli2801** [Multiverse/Multiverse-Inventories#473]
When a player changes their name, only the inventory from the world they logged out will be kept. Every other inventory will be deleted and is lost.

**Comment by badrpc** [comment]
Something similar happened today to my son's account. He renamed it and when he logged in back into our local server his inventory was empty. I ended up renaming all files in plugins/Multiverse-Inventories which had the old nick in the filename and manually edited all files which included the old nick in contents and it looks like it worked. I think our server has Multiverse-Inventories 4.2.3, I'm not sure whether it includes changes mentioned above or not.

**Comment by zax71** [comment]
Duplicate of #329
