### ISSUE TITLE
MV-Inv with MA allows spawning/hacking items

### ISSUE THREAD

**Issue by paulj1x** [Multiverse/Multiverse-Inventories#48]
What steps will reproduce the problem? (Leave blank if you don't know)
1.  We have both creative and survival worlds using MultiVerse/MultiVerse inventories
2.  If a player stocks up on items in creative, then joins MobArena, when they die they bring all of the items from creative into survival
   3.

What happens when you follow these steps? What should happen instead?
 items from creative world should not be brought into survival world

What versions are you using?
 Multiverse-Inventories 2.4-b126, MobArena 0.94.4.65, CraftBukkit git-Bukkit-1.2.5-R1.0-b2149jnks (MC: 1.2.5)

Do you have an error log of what happened? (Please use http://pastebin.com/)
 no errors

Please provide any additional information below.

**Comment by dumptruckman** [comment]
A long time ago I recall discussing this with the dev of MobArena and decided it was something he would have to fix. I even pointed out exactly what would need to change and I believe he decided against changing it. I'm not sure what the status of this is now.
