### ISSUE TITLE
Error occurred while enabling Multiverse-Inventories v4.2.2-b500 (Is it up to date?)

### ISSUE THREAD

**Issue by daencore** [Multiverse/Multiverse-Inventories#486]
### Information

* **Server version: https://pastebin.com/gMRAmRhc** 

* **Full output of `/mv version -p`: https://pastebin.com/se8P6A6z** 

* **Server log: https://gist.github.com/daencore/8f1002494f46c65fdbc2040a89d9d774.js** 

### Help request

**Problem**
Multiverse-Inventories wont Start, i become the error:
Error occurred while enabling Multiverse-Inventories v4.2.2-b500 (Is it up to date?)

**What I have tried**
Delete the Multiverse-Inventories JAR and Folder, but dosent have any affect. I Dont know whats wrong. pls Help
Thank you

**Comment by benwoo1110** [comment]
See #480
