### ISSUE TITLE
4.2.c-SNAPSHOT-b522 error

### ISSUE THREAD

**Issue by JFCCoding12** [Multiverse/Multiverse-Inventories#487]
### Information

* **Server version: 
* This server is running Paper version git-Paper-181 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 2121aed)
You are running the latest version
Previous version: git-Paper-177 (MC: 1.18.1)

* **Full output of `/mv version -p`: 
* https://paste.gg/cb1038f36658493a9f41a428c9a6fd77

* **Server log: https://gist.github.com/JFCCoding12/3f3cc4440e7d6d575f3e13980dbfe948

### Details

**Description**  
When I try to run it fails every time. Looks like it is an overflow. 

**Steps to reproduce**  
started server

**Expected behavior**  
it to work

**Comment by benwoo1110** [comment]
Get the latest dev builds, see #480 for more details on the issue.
