### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by xDItsTej** [Multiverse/Multiverse-Inventories#489]
### Information

* **Server version:**  Paper version git-Paper-194 (MC: 1.18.1)

* **Full output of `/mv version -p`:** https://paste.gg/658fb6f565a243968bee0c598a1a6e73

* **Server log:** (https://mclo.gs/AxKjuMm)

### Help request

**Problem**
My server crashes anytime someone joins

**What I have tried**
Restarting the server

**Screenshots**
![unknown](https://user-images.githubusercontent.com/97074458/153723768-1d359dfc-e210-4c8f-94d0-0357f7cccb04.png)

**Comment by benwoo1110** [comment]
Update mvinv, see #480
