### ISSUE TITLE
Multiverse-Inventories fails to load on 1.18.2

### ISSUE THREAD

**Issue by krystofkrticka** [Multiverse/Multiverse-Inventories#496]
### Information

* **Server version:** This server is running Paper version git-Paper-238 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 657d163)

* **Full output of `/mv version -p`:** https://paste.gg/01122974ccfb42f990b6291d47eaf495

* **Server log:** https://gist.github.com/krystofkrticka/14cf86e0bb735516d3724343a5275765

### Details
I was **`able`** to reproduce my issue on a freshly setup and up-to-date server with the latest version of Multiverse plugins with no other plugins and with no kinds of other server or client mods.

**Description**  
When starting server I saw that it spit out some error so I scrolled to that error message and found out that Multiverse.Inventories failed to load. I tested this even with latest available builds on Jenkins.

**Steps to reproduce**  
Just start server for 1.18.2 with Multiverse installed

**Expected behavior**  
Multiverse.Inventories would load and work just like before updating to 1.18.2

**Screenshots**  
![image](https://user-images.githubusercontent.com/37749100/157906726-f06c8d04-f057-47aa-9010-76af31a7b3af.png)

**Comment by Taemin27** [comment]
Got the same problem too. 
![image](https://user-images.githubusercontent.com/56300365/158003023-17dfa6a1-ca61-46a2-81b8-3bdc4957bf22.png)
Seems like downgrading to 1.18.1 is the only option now.

**Comment by nicegamer7** [comment]
Looks like a duplicate of #480. Please open your config files (config.yml and groups.yml), remove all extra comments and whitespace, the try the latest snapshots.

**Comment by krystofkrticka** [comment]
@Taemin27 I already tried that, but I already don't have my 1.18.1 map I upgraded it to 1.18.2.

**Comment by krystofkrticka** [comment]
@nicegamer7 I see what probably happened here this is what I see when I enable showing ends of lines.
![image](https://user-images.githubusercontent.com/37749100/158009433-d1dee948-a855-4be0-9adf-ad2b887eb320.png)

**Comment by krystofkrticka** [comment]
@nicegamer7 Thanks cleaning those files and updating to latest snapshot build from jenkins fixed this.

**Comment by krystofkrticka** [comment]
@Taemin27 that what @nicegamer7 wrote did the trick and plugin works just like before, but without regex it PITA to remove those additional lines and duplicate comments.
