### ISSUE TITLE
Werid Error

### ISSUE THREAD

**Issue by PaladinFallen** [Multiverse/Multiverse-Inventories#516]
### Information

* **Server version:** Paper 418

* **Full output of `/mv version -p`:** https://bit.ly/3KzCeZv

* **Server log:** https://gist.github.com/PaladinFallen/f544583fefa2a10a8669f518c85f0d1a

### Details
This has only happened with the newer versions of Paper

**Description**  
An error occured while loading plugin.yml resource for plugin Multiverse-Inventories:
org.yaml.snakeyaml.constructor.ConstructorException: could not determine a constructor for the tag !@UTF8
 in 'reader', line 111, column 3:
    - !@UTF8

**Steps to reproduce**  
Start the server

**Expected behavior**  
Not to show the error on the log

**Comment by benwoo1110** [comment]
You can get the patched version at https://github.com/Multiverse/Multiverse-Inventories/releases/tag/4.2.5

we will update DBO site soon
