### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by ItzMaroYT** [Multiverse/Multiverse-Inventories#526]
# Error while opening multiverse-inventories
- i did /pl and i see multiverse-inventories with red color
- and when i do /mvinvreload or any command of multiverse-inventories sent to me "an internal error accurred while attempting to perform this command"

# Console Logs
- [Pastebin.com - log](https://pastebin.com/0SUUV0ZN)

**Comment by ItzMaroYT** [comment]
Can someone help me?

**Comment by ItzMaroYT** [comment]
CAN SOMEONE HELP ME?

**Comment by zax71** [comment]
No support is provided for offline mode servers
