### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by DjSneijder** [Multiverse/Multiverse-Inventories#527]
**Problem**
When I turn on my server in the console it sends me the following message that will be in the image

**What I have tried**
I haven't tried anything

**Screenshots**
![Anotación 2023-08-16 122829](https://github.com/Multiverse/Multiverse-Inventories/assets/114528547/9d3b2252-1709-437a-9583-62144fa9f1d2)

**Comment by zax71** [comment]
The Multiverse Team is aware of the deprecated event that you're informed about in your server logs on startup. The "performance impact" is not noticeable. The warning is fine to ignore.
