### ISSUE TITLE
Question about keeping seperate inventories per world

### ISSUE THREAD

**Issue by Grinjr** [Multiverse/Multiverse-Inventories#55]
Hey, I have a bunch of survival worlds, and then I just recently made a creative world for people who would like to go creative. But I cannot enable creative in that world quite yet because I cannot figure out how to make a seperate inventory for all the survival worlds, and a seperate inventory for all the creative worlds.

I already have a plugin called DreamLand that does that for dreams, for my dream worlds. But I want to figure out how to do it for the creative worlds.

Thanks for helping

**Comment by dumptruckman** [comment]
This ticket is old and may no longer be relevant. I apologize for not being able to help with it in a timely manner. I am going to close it now but if you feel the issue is still relevant please open a new ticket and I may be able to assist with it this time around.
