### ISSUE TITLE
Usernames - case-sensitive

### ISSUE THREAD

**Issue by ohjays** [Multiverse/Multiverse-Inventories#69]
Ive been running a little lan server for the kids, and a problem i run into from time to
time is case-sensitivity ( its running on Debian GNU Linux ) sometimes one of them logs in
as Kid instead of kid and MV-inventories treats them as separate names - thus separate inventories
any way of fixing this

**Comment by dumptruckman** [comment]
We don't support unauthenticated servers. However, this may be fixed with #306
