### ISSUE TITLE
Last location saving

### ISSUE THREAD

**Issue by dumptruckman** [Multiverse/Multiverse-Inventories#7]
Idea was presented by jamesg in irc.  The basic concept is that your last location would be stored per world group, and when you teleport back into that world group, you would end up at the last location.

This feature needs a lot of planning however to make sure it does not end up confusing players or making them think things are broken.

Probably a configgable feature that is off by default, when turned on, it would be an additional share.  Also have a bypass permission for admins using this.  When in use, it could override all teleports into worlds in that world group (except maybe portals that go to other portals) and teleport you specifcally to where you last left the world group even if it's another world in the group you teleported into.

**Comment by sebas202** [comment]
> Do you know how to make last_location to save for only 1 world(I don't want to save last location for spawn). Sorry for writing to a closed thread.

I have the same problem...

**Comment by fuzzbear101** [comment]
> Do you know how to make last_location to save for only 1 world(I don't want to save last location for spawn). Sorry for writing to a closed thread.

You can ungroup the lobby world and then set "optionals_for_ungrouped_worlds" to false in the mvinv config.yml
