### ISSUE TITLE
Restore/edit player inventories

### ISSUE THREAD

**Issue by Suffice** [Multiverse/Multiverse-Inventories#97]
Due to a bug with another plugin, a player has lost all of their hard earned inventory.

Is there a way to recover the inventory from this saved file? We've already tried overwriting the existing, and restarting the server, with no avail. From what I understand the inventory is stored in the world folder, under some player.dat file. And MV Inv only updates when a player changes worlds.

Below is their most recent inventory before it was erased:

SURVIVAL:
  bedSpawnLocation: wo:lyra;x:-49.0;y:68.0;z:-335.0;pi:0.0;ya:0.0
  enderChestContents: 0:t:327/1:t:327/2:t:327/3:t:327/4:t:327/5:t:327/6:t:327/7:t:327/8:t:327/9:t:327/10:t:327/11:t:327/12:t:327
  armorContents: 0:t:313;d:4;e:PROTECTION_ENVIRONMENTAL:5/1:t:312;d:6;e:PROTECTION_ENVIRONMENTAL:5/2:t:311;d:4;e:PROTECTION_ENVIRONMENTAL:5/3:t:310;d:5;e:PROTECTION_ENVIRONMENTAL:5
  potions: ''
  inventoryContents: 0:t:278;d:308;e:DURABILITY:3,DIG_SPEED:4/1:t:276;d:191;e:DAMAGE_ALL:3,KNOCKBACK:2,FIRE_ASPECT:2/2:t:98;#:12/3:t:98;#:64/4:t:323;#:16/5:t:279;d:227;e:SILK_TOUCH:1/6:t:44;d:5;#:63/7:t:4;#:64/8:t:297;#:33/9:t:109;#:6/10:t:352/11:t:98;#:64/12:t:58;#:4/13:t:54;#:18/14:t:323;#:6/15:t:101;#:7/16:t:20;#:64/17:t:346/18:t:360;#:64/19:t:361/20:t:280;#:16/21:t:86;#:4/22:t:256;d:16/23:t:258;d:93/24:t:344;#:3/25:t:357;#:6/26:t:360;#:14/27:t:87;#:34/28:t:20;#:64/29:t:20;#:64/30:t:20;#:35/31:t:98;#:64/32:t:98;#:64/33:t:98;#:64/34:t:98;#:64/35:t:4;#:64
  stats: xp:0.066828586;fd:0.0;el:40;ft:-20;sa:5.0;ra:300;hp:20;fl:19;ma:300;txp:116948;ex:2.3295903

I can make out very little.. of.. this. .

Is there a trick to recovering the items from one of these files?

**Comment by dumptruckman** [comment]
[This wiki page](https://github.com/Multiverse/Multiverse-Inventories/wiki/Sharing-Details) explains how it all works. Unfortunately this kind of situation is probably not something I'm going to be fixing. I know this response is super late; I'm mostly responding for posterity as I clean up the issue tracker.
